# Generated by Django 5.0.6 on 2026-09-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_verified'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailotp',
            name='users_email_user_id_155caa_idx',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration Verification'), ('password_reset', 'Password Reset')], default='registration', max_length=32),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='users_email_user_id_f6f756_idx'),
        ),
    ]
