# Generated by Django 5.0.6 on 2026-09-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_emailotp_users_email_user_id_155caa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration Verification'), ('password_reset', 'Password Reset'), ('login', 'Login Verification')], default='registration', max_length=32),
        ),
    ]
