# Generated by Django 5.0.6 on 2026-09-12 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.TextField()),
                ('delivery_location', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting Volunteer Assignment'), ('ASSIGNED', 'Volunteer Assigned'), ('IN_TRANSIT', 'Volunteer In Transit'), ('PICKED_UP', 'Food Picked Up'), ('DELIVERED', 'Food Delivered to NGO'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='donations.fooddonation')),
            ],
            options={
                'verbose_name': 'pickup',
                'verbose_name_plural': 'pickups',
            },
        ),
    ]
