# Generated by Django 5.0.6 on 2026-09-12 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pickups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['status'], name='pickups_pic_status_176db6_idx'),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['volunteer'], name='pickups_pic_volunte_f66394_idx'),
        ),
    ]
