# Generated by Django 5.0.6 on 2026-09-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Awaiting Volunteer Assignment'), ('ASSIGNED', 'Volunteer Assigned'), ('PICKED_UP', 'Food Picked Up'), ('DELIVERED', 'Food Delivered to NGO'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25),
        ),
    ]
