# Generated by Django 5.0.6 on 2026-09-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_servings', models.PositiveIntegerField(help_text='Number of servings requested for distribution.')),
                ('message', models.TextField(blank=True, help_text='Purpose / beneficiary details (e.g., homeless shelter, community meal).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Donor Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by NGO')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': 'donation request',
                'verbose_name_plural': 'donation requests',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='UI icon name or emoji', max_length=50)),
            ],
            options={
                'verbose_name': 'food category',
                'verbose_name_plural': 'food categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('dietary_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan'), ('EGG', 'Contains Egg')], default='VEG', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms (kg)'), ('meals', 'Meals / Servings'), ('packets', 'Packets / Boxes'), ('liters', 'Liters (L)')], default='meals', max_length=20)),
                ('servings', models.PositiveIntegerField(default=10, help_text='Estimated number of people this donation can feed.')),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_at', models.DateTimeField(help_text='Food safety expiration deadline. Must be strictly respected.')),
                ('pickup_address', models.TextField(help_text='Full physical address where the food can be collected.')),
                ('pickup_city', models.CharField(default='Local', max_length=100)),
                ('pickup_contact_phone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REQUESTED', 'Requested by NGO'), ('ACCEPTED', 'Claim Accepted'), ('PICKUP_ASSIGNED', 'Pickup Assigned'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered to NGO'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=25)),
                ('special_instructions', models.TextField(blank=True, help_text='Storage requirements, refrigeration notes, container instructions.')),
            ],
            options={
                'verbose_name': 'food donation',
                'verbose_name_plural': 'food donations',
            },
        ),
    ]
