# Generated by Django 5.0.6 on 2026-09-12 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donations.foodcategory'),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.fooddonation'),
        ),
        migrations.AddIndex(
            model_name='fooddonation',
            index=models.Index(fields=['status'], name='donations_f_status_4c3735_idx'),
        ),
        migrations.AddIndex(
            model_name='fooddonation',
            index=models.Index(fields=['expiry_at'], name='donations_f_expiry__50c7be_idx'),
        ),
        migrations.AddIndex(
            model_name='fooddonation',
            index=models.Index(fields=['donor'], name='donations_f_donor_i_8841e4_idx'),
        ),
        migrations.AddIndex(
            model_name='fooddonation',
            index=models.Index(fields=['pickup_city'], name='donations_f_pickup__ee3035_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['status'], name='donations_d_status_8939ae_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['receiver'], name='donations_d_receive_776b95_idx'),
        ),
        migrations.AddConstraint(
            model_name='donationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED'])), fields=('donation', 'receiver'), name='unique_active_request_per_receiver'),
        ),
    ]
