# Generated by Django 5.0.6 on 2026-09-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this category is active and selectable for donations.'),
        ),
    ]
