# Generated by Django 5.0.6 on 2026-09-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_foodcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='other_food_item',
            field=models.CharField(blank=True, help_text="Specific food item description when category is 'Other'.", max_length=100, null=True),
        ),
    ]
